[build]
  publish = "dist"
  command = "npm run build"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[headers]]
  for = "/netlify-forms.html"
  [headers.values]
    X-Robots-Tag = "noindex"

# Configuration pour les formulaires
[forms]
  enabled = true

# Redirections après soumission de formulaire
# Ces règles s'appliquent après que Netlify ait traité le formulaire
[[redirects]]
  from = "/fr/contact"
  to = "/fr/merci"
  status = 303
  conditions = {Role = ["netlify"]}
  force = false
  query = {form = ["contact-fiduciaire"]}

[[redirects]]
  from = "/en/contact"
  to = "/en/contact/thank-you"
  status = 303
  conditions = {Role = ["netlify"]}
  force = false
  query = {form = ["contact-fiduciaire"]}