[build]
  publish = "dist"
  command = "npm run build"

# ===========================================
# REDIRECTIONS 301 PERMANENTES (anciennes URLs)
# ===========================================

# 1. Redirections directes vers les URLs finales
[[redirects]]
  from = "/services"
  to = "/fr/services"
  status = 301
  force = true

[[redirects]]
  from = "/comptabilite"
  to = "/fr/comptabilite"
  status = 301
  force = true

[[redirects]]
  from = "/fiscalite"
  to = "/fr/fiscalite"
  status = 301
  force = true

[[redirects]]
  from = "/creation-societe-luxembourg"
  to = "/fr/creation-societe-luxembourg"
  status = 301
  force = true

[[redirects]]
  from = "/paie"
  to = "/fr/paie"
  status = 301
  force = true

[[redirects]]
  from = "/domiciliation"
  to = "/fr/domiciliation"
  status = 301
  force = true

[[redirects]]
  from = "/a-propos"
  to = "/fr/a-propos"
  status = 301
  force = true

[[redirects]]
  from = "/contact"
  to = "/fr/contact"
  status = 301
  force = true

[[redirects]]
  from = "/articles"
  to = "/fr/articles"
  status = 301
  force = true

[[redirects]]
  from = "/articles/*"
  to = "/fr/articles/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/mentions-legales"
  to = "/fr/mentions-legales"
  status = 301
  force = true

[[redirects]]
  from = "/politique-confidentialite"
  to = "/fr/politique-confidentialite"
  status = 301
  force = true

# Redirections pour anciennes URLs company-formation
[[redirects]]
  from = "/company-formation"
  to = "/fr/creation-societe-luxembourg"
  status = 301
  force = true

[[redirects]]
  from = "/en/company-formation"
  to = "/en/company-formation-luxembourg"
  status = 301
  force = true

[[redirects]]
  from = "/constitution-sarl"
  to = "/fr/creation-societe-luxembourg"
  status = 301
  force = true

# 2. DÉTECTION DE LANGUE pour la page d'accueil (une seule redirection)
# Redirection par défaut vers le français
[[redirects]]
  from = "/"
  to = "/fr/"
  status = 301
  force = true

# Note: Pas de catch-all /* car cela peut interférer avec les assets statiques

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[headers]]
  for = "/netlify-forms.html"
  [headers.values]
    X-Robots-Tag = "noindex"

# Configuration pour les formulaires
[forms]
  enabled = true

# Redirections après soumission de formulaire
# Ces règles s'appliquent après que Netlify ait traité le formulaire
[[redirects]]
  from = "/fr/contact"
  to = "/fr/merci"
  status = 303
  conditions = {Role = ["netlify"]}
  force = false
  query = {form = ["contact-fiduciaire"]}

[[redirects]]
  from = "/en/contact"
  to = "/en/contact/thank-you"
  status = 303
  conditions = {Role = ["netlify"]}
  force = false
  query = {form = ["contact-fiduciaire"]}
